window.QM_CONTENT_SCHEMA = [
  {
    id: "hero",
    label: "Abertura",
    description: "Título e apresentação principal da página.",
    fields: [
      { key: "hero.title_start", label: "Título — primeira linha", defaultValue: "Seu mercado funciona" },
      { key: "hero.title_highlight", label: "Destaque do título", defaultValue: "24h." },
      { key: "hero.title_end", label: "Título — segunda linha", defaultValue: "Você não precisa." },
      { key: "hero.description", label: "Texto principal", type: "textarea", defaultValue: "Uma franquia de varejo autônomo com reconhecimento facial, self-checkout, gestão remota e dados para acompanhar a operação, sem atendentes no ponto de venda." },
    ],
  },
  {
    id: "about",
    label: "Marca e apresentação",
    description: "Textos da faixa de marcas e da seção sobre o negócio.",
    fields: [
      { key: "brands.title", label: "Título das marcas", defaultValue: "Marcas que fazem parte da experiência Que Mercado." },
      { key: "brands.description", label: "Texto das marcas", type: "textarea", defaultValue: "Um mix reconhecido ajuda a transformar conveniência em hábito de compra." },
      { key: "about.title", label: "Título da apresentação", defaultValue: "Mercado perto de quem compra. Gestão na mão de quem opera." },
      { key: "about.paragraph_1", label: "Parágrafo 1", type: "textarea", defaultValue: "O Que Mercado leva uma loja completa para dentro da rotina das pessoas: no condomínio, na empresa ou em um ponto de grande circulação. O cliente entra, pega o que precisa e paga sozinho, inclusive fora do horário comercial." },
      { key: "about.paragraph_2", label: "Parágrafo 2", type: "textarea", defaultValue: "Para o franqueado, a lógica também é simples: acompanhar vendas, estoque e operação sem precisar passar o dia atrás de um balcão. O atendimento acontece pela tecnologia; a gestão continua com você." },
      { key: "about.paragraph_3", label: "Parágrafo 3", type: "textarea", defaultValue: "É varejo de verdade, com produto na prateleira, giro, reposição e decisão. A diferença é que boa parte do trabalho repetitivo deixa de depender de uma pessoa parada no caixa." },
    ],
  },
  {
    id: "operation",
    label: "Operação e tecnologia",
    description: "Comparativo, tecnologia, funcionamento e benefícios.",
    fields: [
      { key: "compare.title", label: "Título do comparativo", defaultValue: "Você quer empreender, não contratar um segundo emprego." },
      { key: "compare.retail_title", label: "Título — varejo tradicional", defaultValue: "A rotina cobra presença." },
      { key: "compare.qm_title", label: "Título — Que Mercado", defaultValue: "A tecnologia assume o balcão." },
      { key: "compare.ending_title", label: "Fechamento do comparativo", defaultValue: "Você não precisa viver isso." },
      { key: "compare.ending_text", label: "Texto do fechamento", type: "textarea", defaultValue: "Conheça uma operação que reduz a dependência do atendimento presencial." },
      { key: "technology.title", label: "Título da tecnologia", defaultValue: "Do acesso à reposição, a operação acontece com dados." },
      { key: "technology.description", label: "Texto da tecnologia", type: "textarea", defaultValue: "O modelo conecta a experiência do cliente à gestão do franqueado: acesso, pagamento, estoque, monitoramento e tomada de decisão." },
      { key: "how.title", label: "Título de como funciona", defaultValue: "Comprar é simples. Operar também precisa ser." },
      { key: "benefits.title", label: "Título dos benefícios", defaultValue: "Uma operação pensada para crescer sem virar um peso." },
    ],
  },
  {
    id: "models",
    label: "Modelos de negócio",
    description: "Apresentação, textos e investimentos dos dois modelos.",
    fields: [
      { key: "models.title", label: "Título da seção", defaultValue: "Você escolhe onde o seu Que Mercado vai funcionar." },
      { key: "models.description", label: "Texto da seção", type: "textarea", defaultValue: "2 modelos de negócio. 1 sistema. Uma operação adaptada ao espaço e ao perfil de consumo de cada ponto." },
      { key: "models.company.title", label: "Modelo Empresa — nome", defaultValue: "Modelo Empresa" },
      { key: "models.company.lead", label: "Modelo Empresa — chamada", type: "textarea", defaultValue: "Dentro da empresa, para quem trabalha perto." },
      { key: "models.company.description", label: "Modelo Empresa — descrição", type: "textarea", defaultValue: "Uma solução de conveniência para escritórios e empresas, sem cantina tradicional e sem equipe fixa de atendimento." },
      { key: "models.company.price", label: "Modelo Empresa — investimento", defaultValue: "R$ 15.000" },
      { key: "models.container.title", label: "Contêiner/Condomínio — nome", defaultValue: "Modelo Contêiner e/ou Condomínio" },
      { key: "models.container.lead", label: "Contêiner/Condomínio — chamada", type: "textarea", defaultValue: "Uma estrutura completa para áreas residenciais ou pontos de grande circulação." },
      { key: "models.container.description", label: "Contêiner/Condomínio — descrição", type: "textarea", defaultValue: "Uma loja autônoma adaptada ao local de implantação, com acesso digital, self-checkout e operação sem atendente permanente." },
      { key: "models.container.price", label: "Contêiner/Condomínio — investimento", defaultValue: "R$ 65.000" },
    ],
  },
  {
    id: "conversion",
    label: "Oportunidade e conversão",
    description: "Oportunidade, jornada, formulário e chamada final.",
    fields: [
      { key: "opportunity.title", label: "Título da oportunidade", defaultValue: "A conveniência já virou um hábito, mas poucos estão explorando." },
      { key: "opportunity.paragraph_1", label: "Oportunidade — parágrafo 1", type: "textarea", defaultValue: "O Que Mercado destaca um universo de mais de 200 mil condomínios no Brasil e afirma que menos de 10% contam hoje com algum modelo de mercado autônomo." },
      { key: "opportunity.paragraph_2", label: "Oportunidade — parágrafo 2", type: "textarea", defaultValue: "Para o franqueado, isso abre espaço para prospectar pontos com circulação recorrente e demanda por conveniência." },
      { key: "journey.title", label: "Título da jornada", defaultValue: "Um caminho claro para começar." },
      { key: "lead.title", label: "Título do formulário", defaultValue: "Descubra se o Que Mercado combina com seu perfil." },
      { key: "lead.description", label: "Texto do formulário", type: "textarea", defaultValue: "Faça um pré-cadastro rápido e converse com o time de expansão." },
      { key: "cta.title", label: "Chamada final — primeira linha", defaultValue: "Seu próximo negócio pode funcionar 24 horas." },
      { key: "cta.highlight", label: "Chamada final — destaque", defaultValue: "Sem precisar de você 24 horas." },
      { key: "cta.description", label: "Chamada final — texto", type: "textarea", defaultValue: "Converse com o time de expansão e descubra se o Que Mercado faz sentido para o seu perfil e região." },
    ],
  },
  {
    id: "blog_faq",
    label: "Blog, FAQ e rodapé",
    description: "Chamadas editoriais e informações de encerramento.",
    fields: [
      { key: "blog.title", label: "Título do blog na home", defaultValue: "Conteúdo para quem quer entender o varejo autônomo." },
      { key: "blog.description", label: "Texto do blog na home", type: "textarea", defaultValue: "Artigos do blog Que Mercado sobre franquias, empresas e novos hábitos de consumo." },
      { key: "faq.title", label: "Título do FAQ", defaultValue: "As dúvidas que realmente importam antes de investir." },
      { key: "footer.description", label: "Texto do rodapé", type: "textarea", defaultValue: "Franquia de mercado autônomo com tecnologia, gestão remota e formatos para diferentes espaços." },
    ],
  },
];
