
const WHATSAPP_NUMBER='5551996456479';
const defaultMsg='Olá! Conheci a franquia Que Mercado pelo site e gostaria de receber mais informações.';
const $=(s,c=document)=>c.querySelector(s), $$=(s,c=document)=>[...c.querySelectorAll(s)];
$$('[data-year]').forEach(el=>el.textContent=new Date().getFullYear());
$$('.whatsapp-link').forEach(a=>{const m=a.dataset.message||defaultMsg;a.href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(m)}`;a.target='_blank';});
const toggle=$('.menu-toggle'), mobile=$('.mobile-menu'); if(toggle&&mobile){toggle.onclick=()=>{const open=mobile.classList.toggle('open');toggle.setAttribute('aria-expanded',open);mobile.setAttribute('aria-hidden',!open)};$$('a',mobile).forEach(a=>a.onclick=()=>mobile.classList.remove('open'))}
// synchronized comparison
const compare=$('[data-scroll-compare]'); if(compare){const left=$$('[data-compare-item]',compare),right=$$('[data-gain-item]',compare),total=Math.min(left.length,right.length);let ticking=false;const update=()=>{const r=compare.getBoundingClientRect(),vh=innerHeight,start=vh*.42,travel=Math.max(vh*.78,680),p=Math.max(0,Math.min(1,(start-r.top)/travel)),done=Math.max(0,Math.min(total,Math.floor(p*total+.0001)));left.forEach((x,i)=>x.classList.toggle('done',i<done));right.forEach((x,i)=>x.classList.toggle('on',i<done));ticking=false};addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update);update()}
// technology rotator: only runs while visible and always starts at 01
const tech=$('[data-tech-rotator]'); if(tech){const data=[['◎','Reconhecimento facial','Controle de entrada e identificação do usuário conforme a configuração da unidade.',['ACESSO','SEGURANÇA','RASTREABILIDADE']],['↻','Estoque inteligente','Acompanhamento de giro e apoio à reposição para reduzir ruptura.',['GIRO','REPOSIÇÃO','EFICIÊNCIA']],['↗','Dados em tempo real','Vendas, estoque e performance acessíveis remotamente.',['VENDAS','PERFORMANCE','DECISÃO']],['▦','Catálogo estratégico','Mix orientado pelo comportamento de consumo e pela realidade de cada ponto.',['MIX','CONSUMO','GIRO']],['◉','Monitoramento remoto','Câmeras, sensores e controle de acesso ajudam a acompanhar a unidade.',['CÂMERAS','SENSORES','CONTROLE']],['⌁','Gestão à distância','A operação foi desenhada para reduzir a necessidade de presença contínua no ponto.',['REMOTO','24H','AUTONOMIA']]];const tabs=$$('.tech-tab',tech),stage=$('.tech-stage',tech),icon=$('.tech-icon',stage),title=$('h3',stage),text=$('p',stage),count=$('.tech-count',stage),tags=$('.tech-tags',stage),bar=$('.tech-progress span',stage);let idx=0,timer=null,visible=false;const render=i=>{idx=(i+data.length)%data.length;tabs.forEach((t,n)=>t.classList.toggle('active',n===idx));const d=data[idx];icon.textContent=d[0];title.textContent=d[1];text.textContent=d[2];count.textContent=`${String(idx+1).padStart(2,'0')} / 06`;tags.innerHTML=d[3].map(x=>`<span>${x}</span>`).join('');bar.classList.remove('running');void bar.offsetWidth;if(visible&&!matchMedia('(prefers-reduced-motion: reduce)').matches)bar.classList.add('running')};const stop=()=>{clearInterval(timer);timer=null;bar.classList.remove('running')};const start=()=>{stop();if(visible&&!matchMedia('(prefers-reduced-motion: reduce)').matches){render(idx);timer=setInterval(()=>render(idx+1),5000)}};tabs.forEach((t,i)=>t.onclick=()=>{render(i);start()});render(0);stop();new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(visible){idx=0;render(0);start()}else stop()},{threshold:.35}).observe(tech)}
// mobile steps auto carousel
const steps=$('[data-steps-track]');if(steps){const cards=[...steps.children],dots=$$('.steps-dots i');let idx=0,timer;const mobile=()=>innerWidth<=640;const dot=()=>{if(!mobile())return;const center=steps.scrollLeft+steps.clientWidth/2;let best=0,dist=1e9;cards.forEach((c,i)=>{const d=Math.abs(c.offsetLeft+c.offsetWidth/2-center);if(d<dist){dist=d;best=i}});idx=best;dots.forEach((d,i)=>d.classList.toggle('active',i===idx))};const go=i=>{if(!mobile())return;idx=(i+cards.length)%cards.length;steps.scrollTo({left:cards[idx].offsetLeft,behavior:'smooth'})};const start=()=>{clearInterval(timer);if(mobile()&&!matchMedia('(prefers-reduced-motion: reduce)').matches)timer=setInterval(()=>go(idx+1),3800)};steps.addEventListener('scroll',dot,{passive:true});new IntersectionObserver(e=>e[0].isIntersecting?start():clearInterval(timer),{threshold:.3}).observe(steps);addEventListener('resize',()=>{if(!mobile()){clearInterval(timer);steps.scrollLeft=0}else start()});dot()}
// counters
const group=$('[data-counter-group]');if(group){let ran=false;new IntersectionObserver(es=>{if(!es[0].isIntersecting||ran)return;ran=true;$$('[data-counter]',group).forEach((el,j)=>{const target=+el.dataset.counter,start=performance.now()+j*80,dur=900;const tick=n=>{const p=Math.max(0,Math.min(1,(n-start)/dur));el.textContent=Math.round(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)})},{threshold:.3}).observe(group)}
// scroll checklist
const journey=$('[data-journey]');if(journey){const items=$$('li',journey),count=$('[data-journey-count]',journey),bar=$('.journey-bar span',journey);const update=()=>{const trigger=innerHeight*.66;let n=0;items.forEach(i=>{const on=i.getBoundingClientRect().top<trigger;i.classList.toggle('checked',on);if(on)n++});count.textContent=n;bar.style.width=`${n/items.length*100}%`};addEventListener('scroll',update,{passive:true});addEventListener('resize',update);update()}
// lead form + localStorage (prototype)
const leadForm=$('#leadForm');if(leadForm){leadForm.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(leadForm),lead=Object.fromEntries(fd.entries());lead.id='L-'+Date.now();lead.createdAt=new Date().toISOString();lead.status='Novo';const leads=JSON.parse(localStorage.getItem('qm_leads')||'[]');leads.unshift(lead);localStorage.setItem('qm_leads',JSON.stringify(leads));const feedback=$('.form-feedback',leadForm);feedback.textContent='Pré-cadastro salvo. Abrindo o WhatsApp para continuar o atendimento…';const msg=`Olá! Meu nome é ${lead.nome}. Fiz o pré-cadastro da franquia Que Mercado. Cidade: ${lead.cidade}. Faixa de investimento: ${lead.investimento}. Prazo: ${lead.prazo}.`;setTimeout(()=>window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`,'_blank'),350)})}
